apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  labels:
    app: inventory-service
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
  selector:
    app: inventory-deployment
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-service
  labels:
    account: inventory-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment-v1
  labels:
    app: inventory-deployment
    version: 0.0.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-deployment
      version: 0.0.1
  template:
    metadata:
      labels:
        app: inventory-deployment
        version: 0.0.1
    spec:
      serviceAccountName: inventory-service
      containers:
        - name: inventory-deployment-v1
          image: ashutoshsahoo/inventory-service
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
            requests:
              memory: "200Mi"
              cpu: "200m"
          securityContext:
            runAsUser: 1000
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: SPRING_DATA_MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: SPRING_DATA_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
