apiVersion: v1
kind: ServiceAccount
metadata:
  name: shipping-service
  labels:
    account: shipping-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-deployment-v1
  labels:
    app: shipping-deployment
    version: 0.0.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping-deployment
      version: 0.0.1
  template:
    metadata:
      labels:
        app: shipping-deployment
        version: 0.0.1
    spec:
      serviceAccountName: shipping-service
      containers:
        - name: shipping-deployment-v1
          image: ashutoshsahoo/shipping-service
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
            requests:
              memory: "200Mi"
              cpu: "200m"
          securityContext:
            runAsUser: 1000
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: SPRING_DATA_MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: SPRING_DATA_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
