apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
    version: "5"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      version: "5"
  template:
    metadata:
      labels:
        app: mongodb
        version: "5"
    spec:
      containers:
        - name: mongodb
          image: mongo:5
          resources:
            limits:
              memory: "200Mi"
              cpu: "200m"
            requests:
              memory: "100Mi"
              cpu: "100m"
          ports:
            - containerPort: 27017
              protocol: TCP
              name: tcp
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap
                  key: database_name
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - name: tcp
      protocol: TCP
      port: 27017
      targetPort: 27017
