apiVersion: v1
kind: Service
metadata:
  labels:
    app: order-service-v1
    version: 0.0.1
  name: order-service-v1
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
  selector:
    app: order-deployment-v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: order-deployment-v1
    version: 0.0.1
  name: order-deployment-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-deployment-v1
  template:
    metadata:
      labels:
        app: order-deployment-v1
        version: 0.0.1
    spec:
      containers:
        - name: order-deployment-v1
          image: ashutoshsahoo/order-service
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
            requests:
              memory: "200Mi"
              cpu: "200m"
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: SPRING_DATA_MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: SPRING_DATA_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
